### ISSUE TITLE
聊天界面不能查看三维视图

### ISSUE THREAD

**Issue by songxing10000** [zyprosoft/ZYChat#12]

**Comment by zyprosoft** [comment]
不理解三维视图是什么，能否讲解一下？

**Comment by songxing10000** [comment]
@zyprosoft 
![snip20161110_1](https://cloud.githubusercontent.com/assets/10040131/20181678/0ccf9bcc-a79a-11e6-90d5-9b9e83529dff.png)

**Comment by zyprosoft** [comment]
懂了，目前还是不能看吗？

**Comment by songxing10000** [comment]
可以了
