### ISSUE TITLE
下载下来运行报错

### ISSUE THREAD

**Issue by 809848367** [zyprosoft/ZYChat#2]
ld: warning: directory not found for option '-L/Users/apple/Desktop/ZYChat-master/ZYChat-EaseMob/ZYChat/Dependcy/EaseMobSDK/EaseMobSDK/lib'
ld: library not found for -lPods-ZYChat
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zyprosoft** [comment]
请运行.workspace后缀的工程文件

**Comment by 809848367** [comment]
ok问题解决了
