### ISSUE TITLE
关于文本的needRenderCache选项

### ISSUE THREAD

**Issue by xilin** [zyprosoft/ZYChat#5]
目前看到代码里的逻辑是在GJGCChatContentEmojiParser中`setupWithString:withPhoneNumbers:withLinkArray:andEmojis:`处理的
```
    BOOL needRenderCache = YES;
    if (phoneNumberArray.count > 0 || linkArray.count > 0) {
        needRenderCache = NO;
    }else{
        if (imageInfos.count > 7) {
            needRenderCache = YES;
        }
    }
```
这个逻辑是预期的设计吗？第二个else分支相当于没有用。另外，不知道有没有做过profile对比？短文本和图片的渲染成本哪个大呢？

谢谢。

**Comment by zyprosoft** [comment]
第二个分支当混排的小表情超过7个的时候是会用到的

**Comment by xilin** [comment]
@zyprosoft 可是默认值已经设为YES
还是说默认值应该是NO?

**Comment by zyprosoft** [comment]
可能我改错了，应该是NO的

**Comment by xilin** [comment]
那这个cache设计的目的其实就只是在emoji图片多于7个的时候才启用？我没有做过profile不知道怎么来比较好~

**Comment by zyprosoft** [comment]
这个是为了防止小表情太多，需要循环绘制，所以如果没有点击事件的话，把它渲染成一张图片就好了

**Comment by xilin** [comment]
做了一下profile，纯文本的时候cache与否都不影响帧率。小表情下下降的是比较厉害。
那是不是可以理解成逻辑其实可以设计成

```
BOOL needRenderCache = phoneNumberArray.count == 0 && linkArray.count == 0;
```

**Comment by zyprosoft** [comment]
有超过7个小表情的时候，做一些截图渲染会比较好一点，小于7个的时候必要性不大其实
