### ISSUE TITLE
聊天页的空cell问题

### ISSUE THREAD

**Issue by xilin** [zyprosoft/ZYChat#7]
https://github.com/zyprosoft/ZYChat/blob/master/ZYChat-EaseMob/ZYChat/ChatDetail/ViewController/Base/GJGCChatDetailViewController.m#L639

https://github.com/zyprosoft/ZYChat/blob/master/ZYChat-EaseMob/ZYChat/ChatDetail/ViewController/Base/GJGCChatDetailViewController.m#L643

这里空cell用的reuseIdentifier不一致？

**Comment by zyprosoft** [comment]
高速滚动的时候会有出错的问题，需要确保一定有一个cell返回，等列表减速之后，其实这个空cell是不会显示的。
